import { Telegraf } from "telegraf";
import { startHandler } from "../handlers/startHandler";
import { fullTokenScanHandler } from "../handlers/fullTokenScanHandler";
import { compactTokenScanHandler } from "../handlers/compactTokenScanHandler";
import { chartScanHandler } from "../handlers/chartScanHandler";
import { limitedChartScanHandler } from "../handlers/limitedChartScanHandler";
import { fancyChartScanHandler } from "../handlers/fancyChartScanHandler";
import { bubbleMapHandler } from "../handlers/bubbleMapHandler";
// import { coingeckoQueryHandler } from '../handlers/coingeckoQueryHandler';
import { dexPaidCheckHandler } from "../handlers/dexPaidCheckHandler";
import { dexTrendingHandler } from "../handlers/dexTrendingHandler";
import { msTrendingHandler } from "../handlers/msTrendingHandler";
import { pfTrendingHandler } from "../handlers/pfTrendinghandler";
// import { spTrendingHandler } from "../handlers/spTrendingHandler";
import { pfQueryHandler } from "../handlers/pfQueryHandler";
import { msQueryHandler } from "../handlers/msQueryHandler";
import { indexHandler } from "../handlers/indexHandler";
import { epochHandler } from "../handlers/epochHandler";
// import { helpHandler } from '../handlers/helpHandler';
// import { aiHandler } from '../handlers/aiHandler';
// import { cryptoHandler } from '../handlers/cryptoHandler';

export const registerCommands = (bot: Telegraf) => {
  bot.start(startHandler);
  bot.command("x", fullTokenScanHandler);
  bot.command("z", compactTokenScanHandler);
  bot.command("c", chartScanHandler);
  bot.command("cx", limitedChartScanHandler);
  bot.command("cc", fancyChartScanHandler);
  bot.command("bm", bubbleMapHandler);
  bot.command("dp", dexPaidCheckHandler);
  bot.command("dt", dexTrendingHandler);
  bot.command("mst", msTrendingHandler);
  bot.command("pft", pfTrendingHandler);
  bot.command("pf", pfQueryHandler);
  bot.command("ms", msQueryHandler);
  bot.command("index", indexHandler);
  bot.command("epoch", epochHandler);
  // bot.help(helpHandler);
  // bot.command('ai', aiHandler);
  // bot.command('crypto', cryptoHandler);
};
